apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k6-backend-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "namespaces"]
  verbs: ["get", "list", "watch", "create", "delete"]

- apiGroups: ["k6.io"]
  resources: ["testruns"]
  verbs: ["get", "list", "watch", "create", "delete"]
