apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-frontend
  namespace: k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-frontend
  template:
    metadata:
      labels:
        app: k6-frontend
    spec:
      containers:
      - name: k6-frontend
        image: 196390795662.dkr.ecr.us-east-1.amazonaws.com/k6-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://k6-backend:5001"
